Added initial state
brunodavi/http-scripts pull request #10
Opened 2024-09-18 03:52 UTC by sailanka02

2024-09-18 13:34 UTC, brunodavi commented on src/httpScript.js
> +  let state = {initialState}
I think it could be better to declare state as a parameter and set the default to an empty object

2024-09-18 14:10 UTC, brunodavi requested changes
I have some suggestions for changes

2024-09-18 14:10 UTC, brunodavi commented on tests/parceHttpScript.test.js
You could separate this correction into another pr and dedicate this one just to the state parameter.

Adding this solution to another pr

`git revert 7a807ad`

2024-09-18 14:10 UTC, brunodavi commented on tests/parceHttpScript.test.js
If possible, could you add a test to this function:

https://github.com/brunodavi/http-script/blob/4054fafdc024bb82653e3b44b1e59b769f472aba/tests/httpScript.test.js#L283-L286

**Example**
```js
assert.strictEqual(
    httpScript(
      'g :1234',
      undefined,
      { userId=1 }
    ).state.userId,

    1
)
```

and check with `npm test`

2024-09-18 14:12 UTC, brunodavi requested changes
Suggestions for changes

2024-09-18 14:12 UTC, brunodavi commented on src/httpScript.js
> +  let state = {initialState}
I think it could be better to declare state as a parameter and set the default to an empty object

2024-09-18 15:32 UTC, sailanka02 commented
Ok sorry let me make them into two pull requests! I am still learning thanks for being patient.

2024-09-18 15:36 UTC, closed without merging

2024-09-19 11:44 UTC, brunodavi commented
> Ok sorry let me make them into two pull requests! I am still learning thanks for being patient.

I appreciate your interest in the project, you are doing great